
    ##################################################
    ###   Visit https://github.com/tinybirdco/ci   ###
    ###   for more details or custom CI/CD         ###
    ##################################################

    name: Tinybird - CD Workflow

    on:
      workflow_dispatch:
      push:
        branches:
          - main
          - master
        paths:
          - 'tinybird/**'
    jobs:
      cd:
        uses: tinybirdco/ci/.github/workflows/cd.yml@main
        with:
          tb_deploy: true
          data_project_dir: tinybird
        secrets:
          tb_admin_token: ${{ secrets.TB_ADMIN_TOKEN }}
          tb_host: https://ui.us-east.tinybird.co
